### ISSUE TITLE
Fullscreen hotkey not working

### ISSUE THREAD

**Issue by bhajneet** [shabados/presenter#667]
# Describe the bug

Can't full screen on windows, possibly introduced by fixing mac hotkeys

# Step to reproduce behavior

1. 

# Expected behavior

# Screenshots

# Bug environment

 - Device:
 - OS: **Windows**
 - Browser:
 - Version:

**Comment by bhajneet** [comment]
Everything looks good in https://github.com/shabados/presenter/commit/c99270ea526be9440e4a5664c9c4e84ffb618f3a

So I would suggest pulling a reference before this to see if the hotkeys are working to single out this commit. If there is an issue in this commit we have to figure it out for windows users.

@saihaj do you think you can fix this?

**Comment by saihaj** [comment]
I don't have a windows workstation to test so not much I can do. @Harjot1Singh can you take a look?

**Comment by bhajneet** [comment]
Also, idk if you want to bundle in this tracker, but apple+Q is not working on main Shabad OS window on macOS

**Comment by saihaj** [comment]
I don't think it worked before https://github.com/shabados/presenter/pull/548#issuecomment-633157871

**Comment by Harjot1Singh** [comment]
I _believe_ this issue was introduced by updating Electron - the `window.require('electron')` is throwing an exception. Strangely, this is not appearing in Sentry.

I do not believe this is possible to have been introduced in the mac bar settings PR - did you re-install electron after rolling back?

If it isn't that, something has been changed/updated to cause `window.require('electron')` to no longer be valid

**Comment by Harjot1Singh** [comment]
See this breaking change: https://www.electronjs.org/docs/latest/breaking-changes#deprecated-remote-module
